<a href="https://colab.research.google.com/github/raj-learns/American-Express-Data-analysis/blob/main/American_express.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Importing Libraries

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

##Importing Dataset


In [5]:
data_set = pd.read_csv('american_express.csv')
x = data_set.iloc[:,:-1]
y = data_set.iloc[:,-1].values

In [6]:
print(x)

      Credit Score  Geography  Gender  Age  Customer Since  Current Account  \
0              553      Delhi  Female   45               4     0.000000e+00   
1              447  Bengaluru    Male   31               7     0.000000e+00   
2              501      Delhi  Female   32               2     0.000000e+00   
3              428      Delhi    Male   51               3     0.000000e+00   
4              492      Delhi  Female   57               6     1.912682e+06   
...            ...        ...     ...  ...             ...              ...   
9922           594  Bengaluru    Male   28               6     0.000000e+00   
9923           557  Bengaluru    Male   59               3     8.050490e+05   
9924           627     Mumbai  Female   42               4     1.893594e+06   
9925           600  Bengaluru  Female   51               0     9.031778e+05   
9926           553      Delhi    Male   75               7     0.000000e+00   

      Num of products  UPI Enabled  Estimated Yearl

In [7]:
print(y)

[0 0 0 ... 0 1 0]


##Handling missing values

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [9]:
# Separate numeric and categorical columns
numeric_cols = x.select_dtypes(include=[np.number]).columns  # Numeric columns
categorical_cols = x.select_dtypes(include=['object']).columns  # Categorical columns

# Imputer for numeric columns
num_imputer = SimpleImputer(strategy='mean')
x[numeric_cols] = num_imputer.fit_transform(x[numeric_cols])

# Imputer for categorical columns
cat_imputer = SimpleImputer(strategy='most_frequent')
x[categorical_cols] = cat_imputer.fit_transform(x[categorical_cols])

In [10]:
print(x)

      Credit Score  Geography  Gender   Age  Customer Since  Current Account  \
0            553.0      Delhi  Female  45.0             4.0     0.000000e+00   
1            447.0  Bengaluru    Male  31.0             7.0     0.000000e+00   
2            501.0      Delhi  Female  32.0             2.0     0.000000e+00   
3            428.0      Delhi    Male  51.0             3.0     0.000000e+00   
4            492.0      Delhi  Female  57.0             6.0     1.912682e+06   
...            ...        ...     ...   ...             ...              ...   
9922         594.0  Bengaluru    Male  28.0             6.0     0.000000e+00   
9923         557.0  Bengaluru    Male  59.0             3.0     8.050490e+05   
9924         627.0     Mumbai  Female  42.0             4.0     1.893594e+06   
9925         600.0  Bengaluru  Female  51.0             0.0     9.031778e+05   
9926         553.0      Delhi    Male  75.0             7.0     0.000000e+00   

      Num of products  UPI Enabled  Est

In [11]:
x = x.values

In [12]:
print(x)

[[553.0 'Delhi' 'Female' ... 4.0 1.0 274150.0]
 [447.0 'Bengaluru' 'Male' ... 4.0 1.0 519360.0]
 [501.0 'Delhi' 'Female' ... 4.0 1.0 545501.0]
 ...
 [627.0 'Mumbai' 'Female' ... 4.0 0.0 494067.0]
 [600.0 'Bengaluru' 'Female' ... 2.0 1.0 109375.0]
 [553.0 'Delhi' 'Male' ... 4.0 1.0 180031.0]]


##Encoding Categorical Data

In [13]:
from re import L
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [15]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])], remainder= 'passthrough')
x = np.array(ct.fit_transform(x))

In [16]:
print(x)

[[0.0 1.0 0.0 ... 4.0 1.0 274150.0]
 [1.0 0.0 0.0 ... 4.0 1.0 519360.0]
 [0.0 1.0 0.0 ... 4.0 1.0 545501.0]
 ...
 [0.0 0.0 1.0 ... 4.0 0.0 494067.0]
 [1.0 0.0 0.0 ... 2.0 1.0 109375.0]
 [0.0 1.0 0.0 ... 4.0 1.0 180031.0]]


In [17]:
print(x[:10])

[[0.0 1.0 0.0 553.0 0 45.0 4.0 0.0 4.0 1.0 274150.0]
 [1.0 0.0 0.0 447.0 1 31.0 7.0 0.0 4.0 1.0 519360.0]
 [0.0 1.0 0.0 501.0 0 32.0 2.0 0.0 4.0 1.0 545501.0]
 [0.0 1.0 0.0 428.0 1 51.0 3.0 0.0 4.0 1.0 86868.0]
 [0.0 1.0 0.0 492.0 0 57.0 6.0 1912681.501 2.0 1.0 518680.0]
 [0.0 0.0 1.0 649.0 1 61.0 4.0 1739005.126 2.0 1.0 86816.0]
 [0.0 0.0 1.0 624.0 1 54.0 6.0 1741981.923 4.0 1.0 72959.0]
 [1.0 0.0 0.0 510.0 1 74.0 8.0 0.0 4.0 1.0 295115.0]
 [0.0 0.0 1.0 573.0 1 45.0 8.0 1245561.866 4.0 1.0 471174.0]
 [0.0 1.0 0.0 517.0 0 62.0 6.0 2210750.266 4.0 0.0 149488.0]]


##Splitting data into test and training set

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

##Feature Scaling

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [20]:
print(x_train[:2])

[[ 0.99434917 -0.57109746 -0.5792406   0.0182918   1.09615352 -1.09794716
   1.50134279 -1.16977761  0.90580857  0.65086753 -0.06854301]
 [-1.00568294 -0.57109746  1.72639831 -0.80507849 -0.91228097 -0.41311395
   1.50134279  0.93827052  0.90580857  0.65086753  0.34018176]]


##ANN

Initialization

In [21]:
ann = tf.keras.models.Sequential()


Adding input layer and first hidden layer

In [22]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu', input_shape=(x_train.shape[1],)))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Adding second hidden layer

In [23]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding output layer

In [24]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

###ANN Training

compile

In [25]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training on training dataset

In [26]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 120)

Epoch 1/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.4623 - loss: 0.7772
Epoch 2/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8003 - loss: 0.5353
Epoch 3/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7948 - loss: 0.4778
Epoch 4/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8014 - loss: 0.4525
Epoch 5/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8030 - loss: 0.4379
Epoch 6/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8077 - loss: 0.4289
Epoch 7/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8081 - loss: 0.4241
Epoch 8/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8242 - loss: 0.4065
Epoch 9/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8140 - loss: 0.4169
Epoch 10/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8193 - loss: 0.4078
Epoch 11/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8297 - loss: 0.3933
Epoch 12/120
249/249 ━━━━━━━━━━━━━━━━━━━━

##Predictions

single prediction

In [27]:
print(ann.predict(sc.transform([[0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
[[False]]


prediction on test set

In [28]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print( np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [0 1]]


confusion matrix

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1508   65]
 [ 250  163]]


0.8413897280966768